package com.paradisemc.rokidfindmyphone;

import android.app.*; import android.content.*; import android.media.*; import android.net.Uri; import android.os.*;

public final class AlarmController {
 private static final String PREF="alarm_state",CHANNEL="find_phone_alarm"; private static final int ID=9002; private static Ringtone ringtone; private static final Handler handler=new Handler(Looper.getMainLooper()); private static Context appContext;
 private static final Runnable keepLoud=new Runnable(){@Override public void run(){if(appContext==null||!isRinging(appContext))return;forceAudible(appContext);handler.postDelayed(this,1500);}}; private AlarmController(){}
 public static synchronized void start(Context context){Context app=context.getApplicationContext();appContext=app;SharedPreferences p=app.getSharedPreferences(PREF,Context.MODE_PRIVATE);AudioManager audio=(AudioManager)app.getSystemService(Context.AUDIO_SERVICE);NotificationManager nm=(NotificationManager)app.getSystemService(Context.NOTIFICATION_SERVICE);if(!p.getBoolean("ringing",false)){SharedPreferences.Editor e=p.edit();e.putInt("ringer",audio.getRingerMode()).putInt("ringVol",audio.getStreamVolume(AudioManager.STREAM_RING)).putInt("alarmVol",audio.getStreamVolume(AudioManager.STREAM_ALARM)).putInt("notifVol",audio.getStreamVolume(AudioManager.STREAM_NOTIFICATION));if(Build.VERSION.SDK_INT>=23&&nm.isNotificationPolicyAccessGranted()){e.putInt("dnd",nm.getCurrentInterruptionFilter()).putBoolean("hadDndAccess",true);}else e.putBoolean("hadDndAccess",false);e.putBoolean("ringing",true).apply();}forceAudible(app);showAlarmNotification(app);playAlarm(app);handler.removeCallbacks(keepLoud);handler.post(keepLoud);}
 private static void forceAudible(Context app){try{NotificationManager nm=(NotificationManager)app.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=23&&nm.isNotificationPolicyAccessGranted())nm.setInterruptionFilter(NotificationManager.INTERRUPTION_FILTER_ALL);}catch(Exception ignored){}try{AudioManager a=(AudioManager)app.getSystemService(Context.AUDIO_SERVICE);a.setRingerMode(AudioManager.RINGER_MODE_NORMAL);a.setStreamVolume(AudioManager.STREAM_RING,a.getStreamMaxVolume(AudioManager.STREAM_RING),0);a.setStreamVolume(AudioManager.STREAM_NOTIFICATION,a.getStreamMaxVolume(AudioManager.STREAM_NOTIFICATION),0);a.setStreamVolume(AudioManager.STREAM_ALARM,a.getStreamMaxVolume(AudioManager.STREAM_ALARM),0);}catch(Exception ignored){}}
 private static void playAlarm(Context app){try{if(ringtone!=null&&ringtone.isPlaying())return;Uri u=RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM);if(u==null)u=RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE);ringtone=RingtoneManager.getRingtone(app,u);ringtone.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION).build());if(Build.VERSION.SDK_INT>=28)ringtone.setLooping(true);ringtone.play();}catch(Exception ignored){}}
 private static void showAlarmNotification(Context app){NotificationManager nm=(NotificationManager)app.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"Find My Phone alarm",NotificationManager.IMPORTANCE_HIGH);c.setDescription("Alarm used when your Rokid Glasses ask the phone to ring");c.setSound(null,null);c.setBypassDnd(true);c.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);nm.createNotificationChannel(c);}Intent full=new Intent(app,AlarmActivity.class);full.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent fpi=PendingIntent.getActivity(app,1,full,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Intent stop=new Intent(app,StopReceiver.class);stop.setAction("com.paradisemc.rokidfindmyphone.STOP");PendingIntent spi=PendingIntent.getBroadcast(app,2,stop,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(app,CHANNEL):new Notification.Builder(app);Notification n=b.setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle("Your Rokid found this phone").setContentText("Tap STOP when you have found it").setCategory(Notification.CATEGORY_ALARM).setPriority(Notification.PRIORITY_MAX).setVisibility(Notification.VISIBILITY_PUBLIC).setOngoing(true).setAutoCancel(false).setContentIntent(fpi).setFullScreenIntent(fpi,true).addAction(new Notification.Action.Builder(null,"STOP RINGING",spi).build()).build();nm.notify(ID,n);}
 public static synchronized void stop(Context context){Context app=context.getApplicationContext();SharedPreferences p=app.getSharedPreferences(PREF,Context.MODE_PRIVATE);handler.removeCallbacks(keepLoud);try{if(ringtone!=null)ringtone.stop();}catch(Exception ignored){}ringtone=null;AudioManager a=(AudioManager)app.getSystemService(Context.AUDIO_SERVICE);try{a.setStreamVolume(AudioManager.STREAM_RING,p.getInt("ringVol",a.getStreamVolume(AudioManager.STREAM_RING)),0);}catch(Exception ignored){}try{a.setStreamVolume(AudioManager.STREAM_NOTIFICATION,p.getInt("notifVol",a.getStreamVolume(AudioManager.STREAM_NOTIFICATION)),0);}catch(Exception ignored){}try{a.setStreamVolume(AudioManager.STREAM_ALARM,p.getInt("alarmVol",a.getStreamVolume(AudioManager.STREAM_ALARM)),0);}catch(Exception ignored){}try{a.setRingerMode(p.getInt("ringer",AudioManager.RINGER_MODE_NORMAL));}catch(Exception ignored){}try{NotificationManager nm=(NotificationManager)app.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=23&&p.getBoolean("hadDndAccess",false)&&nm.isNotificationPolicyAccessGranted())nm.setInterruptionFilter(p.getInt("dnd",NotificationManager.INTERRUPTION_FILTER_ALL));nm.cancel(ID);}catch(Exception ignored){}p.edit().putBoolean("ringing",false).apply();appContext=null;}
 public static boolean isRinging(Context c){return c.getSharedPreferences(PREF,Context.MODE_PRIVATE).getBoolean("ringing",false);}
}
