package com.paradisemc.rokidfindmyphone;

import android.Manifest; import android.app.*; import android.bluetooth.*; import android.bluetooth.le.*; import android.content.*; import android.content.pm.PackageManager; import android.os.*; import java.nio.charset.StandardCharsets; import java.util.UUID;

public class PhoneFinderService extends Service {
 public static final UUID SERVICE_UUID=UUID.fromString("61f1c7a0-4d57-4b92-8e2b-f2c7b70b1000"), COMMAND_UUID=UUID.fromString("61f1c7a0-4d57-4b92-8e2b-f2c7b70b1001"); private static final String CHANNEL="phone_finder_service"; private static final int NOTIFICATION_ID=9001; private BluetoothGattServer gattServer; private BluetoothLeAdvertiser advertiser; private final AdvertiseCallback advertiseCallback=new AdvertiseCallback(){};
 public static void start(Context c){Intent i=new Intent(c,PhoneFinderService.class);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);} 
 @Override public void onCreate(){super.onCreate();createChannel();startForeground(NOTIFICATION_ID,serviceNotification());startBleServer();}
 @Override public int onStartCommand(Intent i,int f,int id){if(gattServer==null)startBleServer();return START_STICKY;}
 private Notification serviceNotification(){PendingIntent pi=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE); Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);return b.setSmallIcon(android.R.drawable.stat_sys_data_bluetooth).setContentTitle("Rokid Phone Finder ready").setContentText("Listening for Find My Phone from your glasses").setContentIntent(pi).setOngoing(true).build();}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"Phone Finder connection",NotificationManager.IMPORTANCE_LOW);c.setDescription("Keeps the Bluetooth phone-finder receiver available");((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
 private boolean hasBlePermissions(){return Build.VERSION.SDK_INT<31||(checkSelfPermission(Manifest.permission.BLUETOOTH_ADVERTISE)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED);}
 private void startBleServer(){if(!hasBlePermissions())return;BluetoothManager manager=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE);BluetoothAdapter adapter=manager.getAdapter();if(adapter==null||!adapter.isEnabled()||!adapter.isMultipleAdvertisementSupported())return;
  gattServer=manager.openGattServer(this,new BluetoothGattServerCallback(){@Override public void onServiceAdded(int status,BluetoothGattService s){if(status==BluetoothGatt.GATT_SUCCESS&&SERVICE_UUID.equals(s.getUuid()))beginAdvertising();}@Override public void onCharacteristicWriteRequest(BluetoothDevice d,int req,BluetoothGattCharacteristic ch,boolean prep,boolean resp,int off,byte[] value){boolean ok=false;if(COMMAND_UUID.equals(ch.getUuid())&&value!=null){String cmd=new String(value,StandardCharsets.UTF_8).trim();if("RING".equalsIgnoreCase(cmd)){AlarmController.start(PhoneFinderService.this);ok=true;}else if("STOP".equalsIgnoreCase(cmd)){AlarmController.stop(PhoneFinderService.this);ok=true;}}if(resp&&gattServer!=null)gattServer.sendResponse(d,req,ok?BluetoothGatt.GATT_SUCCESS:BluetoothGatt.GATT_FAILURE,off,null);}});
  BluetoothGattService s=new BluetoothGattService(SERVICE_UUID,BluetoothGattService.SERVICE_TYPE_PRIMARY);BluetoothGattCharacteristic cmd=new BluetoothGattCharacteristic(COMMAND_UUID,BluetoothGattCharacteristic.PROPERTY_WRITE|BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE,BluetoothGattCharacteristic.PERMISSION_WRITE);s.addCharacteristic(cmd);advertiser=adapter.getBluetoothLeAdvertiser();gattServer.addService(s);
 }
 private void beginAdvertising(){if(!hasBlePermissions()||advertiser==null)return;try{advertiser.stopAdvertising(advertiseCallback);}catch(Exception ignored){} AdvertiseSettings st=new AdvertiseSettings.Builder().setAdvertiseMode(AdvertiseSettings.ADVERTISE_MODE_LOW_POWER).setTxPowerLevel(AdvertiseSettings.ADVERTISE_TX_POWER_HIGH).setConnectable(true).setTimeout(0).build();AdvertiseData d=new AdvertiseData.Builder().addServiceUuid(new ParcelUuid(SERVICE_UUID)).setIncludeDeviceName(false).build();advertiser.startAdvertising(st,d,advertiseCallback);}
 @Override public void onDestroy(){if(hasBlePermissions()){try{if(advertiser!=null)advertiser.stopAdvertising(advertiseCallback);}catch(Exception ignored){}try{if(gattServer!=null)gattServer.close();}catch(Exception ignored){}}advertiser=null;gattServer=null;super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
}
